name: Validate Calibration Service

on:
  push:
    branches: [ main ]
    paths:
    - 'Backend/calibration_service/**'
    - '.github/workflows/test_calibration_service.yml'
  pull_request:
    branches: [ main ]
    paths:
    - 'Backend/calibration_service/**'
    - '.github/workflows/test_calibration_service.yml'

jobs:
  install-dependencies:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache Packages
      id: cache-packages
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-packages-${{ hashFiles('Backend/calibration_service/requirements.txt') }}

    - name: Install dependencies
      if: steps.cache-packages.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-dependency
        pip install -r Backend/calibration_service/requirements.txt

  unit-tests:
    needs: install-dependencies
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-packages-${{ hashFiles('Backend/calibration_service/requirements.txt') }}

    - name: Unit tests
      run: |
        export PYTHONPATH=Backend/calibration_service/
        pytest --rootdir=Backend/calibration_service/ Backend/calibration_service/tests/unit

  component-tests:
    needs: unit-tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-packages-${{ hashFiles('Backend/calibration_service/requirements.txt') }}

    - name: Component tests
      run: |
        export PYTHONPATH=Backend/calibration_service/
        pytest --rootdir=Backend/calibration_service/ Backend/calibration_service/tests/component
