# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
    paths:
    - 'Backend/calibration_service/**'
    - '.github/workflows/test_calibration_service.yml'
  pull_request:
    branches: [ main ]
    paths:
    - 'Backend/calibration_service/**'
    - '.github/workflows/test_calibration_service.yml'

jobs:
  validate-calibration-service:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r Backend/calibration_service/requirements.txt
    - name: Test calibration service
      run: |
        export PYTHONPATH=Backend/calibration_service/
        pytest
